# Generated by Django 5.0.6 on 2024-05-29 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cli', models.CharField(max_length=100)),
                ('adr_cli', models.CharField(max_length=200)),
                ('ville_cli', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Melange',
            fields=[
                ('id_melange', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Approvisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine_appro', models.IntegerField()),
                ('quantite_melange', models.PositiveIntegerField()),
                ('melange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvisionnements', to='GestionBoulangerie.melange')),
            ],
        ),
        migrations.CreateModel(
            name='Pain',
            fields=[
                ('id_pain', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('prix_pain_ht', models.DecimalField(decimal_places=2, max_digits=8)),
                ('melange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pains', to='GestionBoulangerie.melange')),
            ],
        ),
        migrations.CreateModel(
            name='Livraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_livraison', models.DateField()),
                ('nombre_pains', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='GestionBoulangerie.client')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livraisons', to='GestionBoulangerie.pain')),
            ],
        ),
    ]
