# Generated by Django 5.0.6 on 2024-05-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBoulangerie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='semaine_appro',
            field=models.DateField(),
        ),
    ]
