# Generated by Django 5.0.6 on 2024-05-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionBoulangerie', '0003_alter_livraison_date_livraison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvisionnement',
            name='semaine_appro',
            field=models.IntegerField(),
        ),
    ]
